"""empty message

Revision ID: a8b97632304f
Revises:
Create Date: 2022-05-06 23:14:25.498178

"""


# revision identifiers, used by Alembic.
revision = "a8b97632304f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
