"""empty message

Revision ID: f0de5d1a1d79
Revises: ae2ae9515a19
Create Date: 2022-05-06 23:30:50.891055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0de5d1a1d79'
down_revision = 'ae2ae9515a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
